"""add_unique_constraint_to_proveedor_nit

Revision ID: a64b033fab0d
Revises: d07c67f7f25f
Create Date: 2025-10-26 11:18:26.165972

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a64b033fab0d'
down_revision = 'd07c67f7f25f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('auditoria', 'id_usuario',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('movimientoinventario', 'id_usuario',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_index(op.f('ix_proveedor_nit'), 'proveedor', ['nit'], unique=True)
    op.alter_column('user', 'fecha_creacion',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'fecha_creacion',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index(op.f('ix_proveedor_nit'), table_name='proveedor')
    op.alter_column('movimientoinventario', 'id_usuario',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('auditoria', 'id_usuario',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
